### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by al3xLvs** [tuxity/rtorrent-php#1]
Salut, (en français)

Je voulais savoir si tu comptes tjrs developper cette lib?
Si oui je veux bien filer un coup de main, et connaitre un peu la feuille de route de ce qu'il reste à finir :)

**Comment by tuxity** [comment]
Oui c'est toujours "actif", je veux développer des libs pour rtorrent en php, js et go pour faciliter le développement de nouveaux projets.

J'ai posé une base tu peux continuer si tu veux je checkerais si tu fais des PR 😊

PS: va être temps que je m'y remette ! 😅

**Comment by tuxity** [comment]
Pour la roadmap il y en a pas vraiment. Le plus important et ce que tu as besoin

**Comment by al3xLvs** [comment]
ok il me faudrait la liste des fichiers du torrent. Je vais regarder ça.

**Comment by tuxity** [comment]
Humm comment ca ? J'ai pas compris ce que tu veux dire

**Comment by al3xLvs** [comment]
Dans rutorrent on peut afficher les fichiers d'un torrent. je crois que c'est avec la methode f.multicall

**Comment by tuxity** [comment]
Oui c'est ca https://github.com/mdevaev/emonoda/wiki/rTorrent-XMLRPC-Reference
